import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const SUPABASE_URL="https://kqeolflqbesqvkwuidcx.supabase.co",SUPABASE_PUBLISHABLE_KEY="sb_publishable_gQY6sALUMDv4GbNx5xUnHA_FZgNJ-2n",SITE_URL="https://eudsonalmeida-afk.github.io/Budget/",THEME_KEY="budget_feliz_theme";
const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storage:window.localStorage}});
const banks=[["PicPay","picpay"],["Inter","inter"],["Bradesco","bradesco"],["Banco do Brasil","bb"],["Itaú","itau"],["Dinheiro / Débito","cash"]];
const emoji={"Alimentação":"🍔","Transporte":"🚗","Casa":"🏠","Lazer":"🎮","Saúde":"💊","Compras":"🛒","Assinatura":"📱","Reforma do quarto":"🛠️","Outros":"✨"};
const $=id=>document.getElementById(id),e={authScreen:$("authScreen"),appRoot:$("appRoot"),authForm:$("authForm"),authTitle:$("authTitle"),authDescription:$("authDescription"),authEmail:$("authEmail"),authPassword:$("authPassword"),authSubmit:$("authSubmit"),authModeToggle:$("authModeToggle"),authMessage:$("authMessage"),logout:$("logout"),syncStatus:$("syncStatus"),accountMenu:$("accountMenu"),accountMenuButton:$("accountMenuButton"),accountMenuPanel:$("accountMenuPanel"),accountEmail:$("accountEmail"),prev:$("prev"),next:$("next"),monthBtn:$("monthBtn"),monthPicker:$("monthPicker"),monthLabel:$("monthLabel"),salaryOut:$("salaryOut"),spentOut:$("spentOut"),balanceOut:$("balanceOut"),balanceMsg:$("balanceMsg"),salaryEdit:$("salaryEdit"),appTabs:$("appTabs"),purchaseMode:$("purchaseMode"),installmentDetails:$("installmentDetails"),purchaseName:$("purchaseName"),installmentCount:$("installmentCount"),installmentStart:$("installmentStart"),amountQuestion:$("amountQuestion"),amountHelp:$("amountHelp"),categories:$("categories"),banks:$("banks"),amount:$("amount"),add:$("add"),noteToggle:$("noteToggle"),note:$("note"),preview:$("preview"),today:$("today"),bankTotals:$("bankTotals"),installmentList:$("installmentList"),installmentSummaryMonth:$("installmentSummaryMonth"),installmentMonthTotal:$("installmentMonthTotal"),newInstallment:$("newInstallment"),filters:$("filters"),count:$("count"),filteredTotal:$("filteredTotal"),list:$("list"),export:$("export"),salaryDialog:$("salaryDialog"),salaryForm:$("salaryForm"),salaryInput:$("salaryInput"),salaryMonth:$("salaryMonth"),salaryClose:$("salaryClose"),salaryCancel:$("salaryCancel"),deleteDialog:$("deleteDialog"),deleteTitle:$("deleteTitle"),deleteMessage:$("deleteMessage"),deleteCancel:$("deleteCancel"),deleteConfirm:$("deleteConfirm"),theme:$("theme"),toast:$("toast")};
let authMode="signin",currentUser=null,month=monthKey(new Date()),monthData={salary:0,expenses:[],installments:[]},category="",bank="",filter="Todos",purchaseType="single",activeTab="launch",pendingDelete=null,toastTimer;
function monthKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`}
function monthDate(k){const[y,m]=k.split("-").map(Number);return new Date(y,m-1,1,12)}
function monthName(k){return new Intl.DateTimeFormat("pt-BR",{month:"long",year:"numeric"}).format(monthDate(k))}
function monthDiff(start,target){const a=monthDate(start),b=monthDate(target);return(b.getFullYear()-a.getFullYear())*12+(b.getMonth()-a.getMonth())}
function money(v){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v)||0)}
function parseMoney(v){return Number(String(v||"").replace(/\./g,"").replace(",",".").replace(/[^\d.-]/g,""))||0}
function maskMoney(v){const d=v.replace(/\D/g,"");return d?(Number(d)/100).toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2}):""}
function todayIso(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function bankClass(n){return banks.find(x=>x[0]===n)?.[1]||"cash"}
function dueInstallments(target=month){return monthData.installments.map(p=>{const index=monthDiff(p.startMonth,target);return index>=0&&index<p.totalInstallments?{...p,currentInstallment:index+1,date:`${target}-01`,isInstallment:true}:null}).filter(Boolean)}
function allMonthEntries(){return[...monthData.expenses,...dueInstallments()]}
function total(list=allMonthEntries()){return list.reduce((s,x)=>s+Number(x.amount),0)}
function setSync(t,state=""){e.syncStatus.textContent=t;e.syncStatus.className=`sync-status ${state}`.trim()}
function toast(t){e.toast.textContent=t;e.toast.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.toast.classList.remove("show"),2300)}
function showAuth(msg="",state=""){e.authScreen.classList.remove("hidden");e.appRoot.classList.add("hidden");e.accountMenu.classList.add("hidden");e.authSubmit.disabled=false;e.authSubmit.textContent=authMode==="signin"?"Entrar":"Criar conta";e.authMessage.textContent=msg;e.authMessage.className=`auth-message ${state}`.trim()}
function showApp(){e.authScreen.classList.add("hidden");e.appRoot.classList.remove("hidden");e.accountMenu.classList.remove("hidden");e.accountEmail.textContent=currentUser?.email||"Conta conectada";window.scrollTo(0,0)}
function friendly(m){if(m.includes("Invalid login credentials"))return"E-mail ou senha incorretos.";if(m.includes("Email not confirmed"))return"Confirme seu e-mail antes de entrar.";if(m.includes("User already registered"))return"Este e-mail já possui uma conta.";return m||"Não foi possível concluir."}
async function handleAuth(ev){ev.preventDefault();e.authSubmit.disabled=true;e.authMessage.textContent=authMode==="signin"?"Entrando…":"Criando conta…";try{if(authMode==="signin"){const{data,error}=await supabase.auth.signInWithPassword({email:e.authEmail.value.trim(),password:e.authPassword.value});if(error)throw error;currentUser=data.session.user;showApp();await loadMonth()}else{const{data,error}=await supabase.auth.signUp({email:e.authEmail.value.trim(),password:e.authPassword.value,options:{emailRedirectTo:SITE_URL}});if(error)throw error;e.authMessage.textContent=data.session?"Conta criada.":"Conta criada. Confirme seu e-mail."}}catch(err){e.authMessage.textContent=friendly(err.message);e.authMessage.className="auth-message error"}finally{e.authSubmit.disabled=false}}
function toggleAuth(){authMode=authMode==="signin"?"signup":"signin";const s=authMode==="signup";e.authTitle.textContent=s?"Criar acesso ao Contaê":"Acessar o Contaê";e.authSubmit.textContent=s?"Criar conta":"Entrar";e.authModeToggle.textContent=s?"Já tenho uma conta":"Ainda não tenho conta";e.authMessage.textContent=""}
async function loadMonth(){if(!currentUser)return;setSync("Sincronizando…");const[b,x,p]=await Promise.all([supabase.from("monthly_budgets").select("salary").eq("user_id",currentUser.id).eq("month",month).maybeSingle(),supabase.from("expenses").select("id,expense_date,category,bank,amount,note,created_at").eq("user_id",currentUser.id).eq("month",month).order("expense_date",{ascending:false}),supabase.from("installment_purchases").select("id,name,category,bank,installment_amount,total_installments,start_month,note,created_at").eq("user_id",currentUser.id).order("created_at",{ascending:false})]);if(b.error||x.error||p.error){console.error(b.error||x.error||p.error);setSync("Erro ao sincronizar","error");toast("Confira se a tabela de parcelamentos foi criada.");return}monthData={salary:Number(b.data?.salary||0),expenses:(x.data||[]).map(r=>({id:r.id,date:r.expense_date,category:r.category,bank:r.bank,amount:Number(r.amount),note:r.note||"",createdAt:r.created_at})),installments:(p.data||[]).map(r=>({id:r.id,name:r.name,category:r.category,bank:r.bank,amount:Number(r.installment_amount),totalInstallments:r.total_installments,startMonth:r.start_month,note:r.note||"",createdAt:r.created_at}))};render();setSync("Sincronizado","ok")}
async function saveSalary(ev){ev.preventDefault();const salary=+parseMoney(e.salaryInput.value).toFixed(2);const{error}=await supabase.from("monthly_budgets").upsert({user_id:currentUser.id,month,salary,updated_at:new Date().toISOString()},{onConflict:"user_id,month"});if(error)return toast("Não foi possível salvar o salário.");monthData.salary=salary;e.salaryDialog.close();render();toast("Salário atualizado.")}
async function addEntry(){const amount=parseMoney(e.amount.value);if(!category)return toast("Escolha uma categoria.");if(!bank)return toast("Escolha como pagou.");if(amount<=0)return toast("Digite um valor maior que zero.");e.add.disabled=true;setSync("Salvando…");if(purchaseType==="installment"){const name=e.purchaseName.value.trim(),count=Number(e.installmentCount.value),start=e.installmentStart.value;if(!name){e.add.disabled=false;return toast("Dê um nome à compra.")}if(!Number.isInteger(count)||count<2){e.add.disabled=false;return toast("Informe pelo menos 2 parcelas.")}if(!start){e.add.disabled=false;return toast("Escolha o mês da primeira parcela.")}const{data,error}=await supabase.from("installment_purchases").insert({user_id:currentUser.id,name,category,bank,installment_amount:+amount.toFixed(2),total_installments:count,start_month:start,note:e.note.value.trim()||null}).select("id,name,category,bank,installment_amount,total_installments,start_month,note,created_at").single();e.add.disabled=false;if(error){console.error(error);return toast("Não foi possível salvar o parcelamento.")}monthData.installments.unshift({id:data.id,name:data.name,category:data.category,bank:data.bank,amount:Number(data.installment_amount),totalInstallments:data.total_installments,startMonth:data.start_month,note:data.note||"",createdAt:data.created_at});resetEntry();switchTab("installments");render();toast("Compra parcelada cadastrada.")}else{const date=month===monthKey(new Date())?todayIso():`${month}-01`;const{data,error}=await supabase.from("expenses").insert({user_id:currentUser.id,month,expense_date:date,category,bank,amount:+amount.toFixed(2),note:e.note.value.trim()||null}).select("id,expense_date,category,bank,amount,note,created_at").single();e.add.disabled=false;if(error)return toast("Não foi possível salvar este gasto.");monthData.expenses.unshift({id:data.id,date:data.expense_date,category:data.category,bank:data.bank,amount:Number(data.amount),note:data.note||"",createdAt:data.created_at});resetEntry();render();toast(`Gasto salvo: ${money(amount)}`)}setSync("Sincronizado","ok")}
async function confirmDelete(){if(!pendingDelete)return;const table=pendingDelete.type==="installment"?"installment_purchases":"expenses";const{error}=await supabase.from(table).delete().eq("id",pendingDelete.id).eq("user_id",currentUser.id);if(error)return toast("Não foi possível excluir.");if(pendingDelete.type==="installment")monthData.installments=monthData.installments.filter(x=>x.id!==pendingDelete.id);else monthData.expenses=monthData.expenses.filter(x=>x.id!==pendingDelete.id);pendingDelete=null;e.deleteDialog.close();render();toast("Registro excluído.")}
function render(){e.monthLabel.textContent=monthName(month);e.monthPicker.value=month;e.installmentStart.value=e.installmentStart.value||month;e.today.textContent=month===monthKey(new Date())?`Hoje • ${new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short"}).format(new Date())}`:"Mês selecionado";const spent=total(),balance=monthData.salary-spent;e.salaryOut.textContent=money(monthData.salary);e.spentOut.textContent=money(spent);e.balanceOut.textContent=money(balance);e.balanceMsg.textContent=monthData.salary<=0?"Cadastre o salário deste mês.":balance<0?"O orçamento passou do limite.":spent?`${Math.min(100,spent/monthData.salary*100).toFixed(0)}% do salário utilizado.`:"Nenhum gasto registrado.";renderBanks();renderInstallments();renderList();preview()}
function renderBanks(){const entries=allMonthEntries();e.bankTotals.innerHTML=banks.map(([n,c])=>{const a=entries.filter(v=>v.bank===n);return`<article class="bank-card ${c}"><span>${esc(n)}</span><strong>${money(total(a))}</strong><small>${a.length} ${a.length===1?"lançamento":"lançamentos"}</small></article>`}).join("")}
function renderInstallments(){const due=dueInstallments();e.installmentSummaryMonth.textContent=monthName(month);e.installmentMonthTotal.textContent=money(total(due));if(!monthData.installments.length){e.installmentList.innerHTML='<div class="empty">🧾<br><b>Nenhuma compra parcelada.</b><p>Cadastre uma no lançamento rápido.</p></div>';return}e.installmentList.innerHTML=monthData.installments.map(p=>{const idx=monthDiff(p.startMonth,month),current=Math.max(0,Math.min(p.totalInstallments,idx+1)),finished=idx>=p.totalInstallments,notStarted=idx<0,percent=finished?100:notStarted?0:current/p.totalInstallments*100,dueText=finished?"Finalizado":notStarted?`Começa em ${monthName(p.startMonth)}`:`Parcela ${current}/${p.totalInstallments} neste mês`,remaining=Math.max(0,p.totalInstallments-current)*p.amount;return`<article class="installment-card"><div><h3>${emoji[p.category]||"✨"} ${esc(p.name)}</h3><p>${esc(p.bank)} • ${esc(p.category)}${p.note?` • ${esc(p.note)}`:""}</p><div class="installment-progress"><span style="width:${percent}%"></span></div><span class="installment-due ${finished?'installment-finished':''}">${dueText}</span></div><div class="installment-numbers"><strong>${money(p.amount)}/mês</strong><small>Restante no ciclo: ${money(remaining)}</small></div><div class="installment-actions"><button data-delete-installment="${p.id}" title="Excluir parcelamento">🗑️</button></div></article>`}).join("")}
function renderList(){let a=allMonthEntries();if(filter!=="Todos")a=a.filter(x=>x.bank===filter);a.sort((x,y)=>y.date.localeCompare(x.date)||(y.createdAt||"").localeCompare(x.createdAt||""));e.count.textContent=`${a.length} ${a.length===1?"lançamento":"lançamentos"}`;e.filteredTotal.textContent=money(total(a));if(!a.length){e.list.innerHTML='<div class="empty">🧾<br><b>Nenhum gasto nesta seleção.</b></div>';return}e.list.innerHTML=a.map(x=>{const[y,m,d]=x.date.split("-"),dt=new Date(+y,+m-1,+d,12),sm=new Intl.DateTimeFormat("pt-BR",{month:"short"}).format(dt).replace(".",""),title=x.isInstallment?`${esc(x.name)} • ${x.currentInstallment}/${x.totalInstallments}`:esc(x.category),note=x.note?` • ${esc(x.note)}`:"";return`<article class="expense ${x.isInstallment?'installment-entry':''}"><div class="date"><b>${d}</b><small>${sm}</small></div><div class="info"><b>${emoji[x.category]||"✨"} ${title}</b><small>${esc(x.bank)}${note}</small></div><span class="tag ${bankClass(x.bank)}">${esc(x.bank)}</span><span class="value">-${money(x.amount)}</span>${x.isInstallment?'':`<button class="trash" data-id="${x.id}">🗑️</button>`}</article>`}).join("")}
function preview(){const amount=parseMoney(e.amount.value),p=[];if(purchaseType==="installment"&&e.purchaseName.value.trim())p.push(e.purchaseName.value.trim());if(category)p.push(`${emoji[category]||"✨"} ${category}`);if(bank)p.push(bank);if(amount)p.push(`${money(amount)}${purchaseType==="installment"?" por parcela":""}`);e.preview.textContent=p.length?p.join(" • "):"Selecione categoria, forma de pagamento e valor."}
function switchTab(tab){activeTab=tab;e.appTabs.querySelectorAll("button").forEach(b=>b.classList.toggle("active",b.dataset.tab===tab));document.querySelectorAll(".tab-page").forEach(p=>p.classList.toggle("active",p.id===`tab-${tab}`));window.scrollTo({top:document.querySelector(".app-tabs").offsetTop-8,behavior:"smooth"})}
function setPurchaseType(type){purchaseType=type;e.purchaseMode.querySelectorAll("button").forEach(b=>b.classList.toggle("active",b.dataset.mode===type));const inst=type==="installment";e.installmentDetails.classList.toggle("hidden",!inst);e.amountQuestion.textContent=inst?"Qual o valor de cada parcela?":"Quanto foi?";e.amountHelp.textContent=inst?"Informe o valor mensal da parcela, não o valor total da compra.":"Informe o valor total deste gasto.";e.add.textContent=inst?"Cadastrar parcelamento ＋":"Adicionar gasto ＋";preview()}
function resetEntry(){category=bank="";e.amount.value=e.note.value=e.purchaseName.value=e.installmentCount.value="";e.installmentStart.value=month;e.note.classList.add("hidden");document.querySelectorAll(".chips button").forEach(b=>b.classList.remove("selected"));setPurchaseType("single")}
function selectChoice(box,b,type){box.querySelectorAll("button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");type==="category"?category=b.dataset.category:bank=b.dataset.bank;preview()}
async function changeMonth(n){const d=monthDate(month);d.setMonth(d.getMonth()+n);month=monthKey(d);filter="Todos";syncFilters();await loadMonth()}
function syncFilters(){e.filters.querySelectorAll("button").forEach(b=>b.classList.toggle("active",b.dataset.filter===filter))}
function openSalary(){e.salaryMonth.textContent=`Defina a renda disponível para ${monthName(month)}.`;e.salaryInput.value=monthData.salary?monthData.salary.toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2}):"";e.salaryDialog.showModal()}
function exportCsv(){const a=allMonthEntries();if(!a.length)return toast("Não há gastos para exportar.");const rows=[["Data","Tipo","Descrição","Categoria","Banco","Valor","Parcela","Observação"],...a.map(x=>[x.date.split("-").reverse().join("/"),x.isInstallment?"Parcela":"Gasto",x.isInstallment?x.name:"",x.category,x.bank,x.amount.toFixed(2).replace(".",","),x.isInstallment?`${x.currentInstallment}/${x.totalInstallments}`:"",x.note||""])],csv="\uFEFF"+rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(";")).join("\n"),url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"})),aTag=document.createElement("a");aTag.href=url;aTag.download=`gastos-${month}.csv`;aTag.click();URL.revokeObjectURL(url)}
e.authForm.onsubmit=handleAuth;e.authModeToggle.onclick=toggleAuth;e.logout.onclick=()=>supabase.auth.signOut();e.accountMenuButton.onclick=()=>{const h=e.accountMenuPanel.classList.toggle("hidden");e.accountMenuButton.setAttribute("aria-expanded",String(!h))};document.addEventListener("click",ev=>{if(!e.accountMenu.contains(ev.target))e.accountMenuPanel.classList.add("hidden")});e.prev.onclick=()=>changeMonth(-1);e.next.onclick=()=>changeMonth(1);e.monthBtn.onclick=()=>e.monthPicker.showPicker?e.monthPicker.showPicker():e.monthPicker.click();e.monthPicker.onchange=async()=>{if(e.monthPicker.value){month=e.monthPicker.value;filter="Todos";syncFilters();await loadMonth()}};e.appTabs.onclick=ev=>{const b=ev.target.closest("[data-tab]");if(b)switchTab(b.dataset.tab)};e.purchaseMode.onclick=ev=>{const b=ev.target.closest("[data-mode]");if(b)setPurchaseType(b.dataset.mode)};e.categories.onclick=ev=>{const b=ev.target.closest("[data-category]");if(b)selectChoice(e.categories,b,"category")};e.banks.onclick=ev=>{const b=ev.target.closest("[data-bank]");if(b)selectChoice(e.banks,b,"bank")};e.amount.oninput=()=>{e.amount.value=maskMoney(e.amount.value);preview()};e.purchaseName.oninput=preview;e.add.onclick=addEntry;e.noteToggle.onclick=()=>{e.note.classList.toggle("hidden");e.noteToggle.textContent=e.note.classList.contains("hidden")?"+ Adicionar observação":"− Ocultar observação"};e.salaryEdit.onclick=openSalary;e.salaryClose.onclick=e.salaryCancel.onclick=()=>e.salaryDialog.close();e.salaryInput.oninput=()=>e.salaryInput.value=maskMoney(e.salaryInput.value);e.salaryForm.onsubmit=saveSalary;e.newInstallment.onclick=()=>{switchTab("launch");setPurchaseType("installment")};e.filters.onclick=ev=>{const b=ev.target.closest("[data-filter]");if(b){filter=b.dataset.filter;syncFilters();renderList()}};e.list.onclick=ev=>{const b=ev.target.closest("[data-id]");if(b){pendingDelete={type:"expense",id:b.dataset.id};e.deleteTitle.textContent="Excluir este gasto?";e.deleteMessage.textContent="O valor voltará ao saldo do mês.";e.deleteDialog.showModal()}};e.installmentList.onclick=ev=>{const b=ev.target.closest("[data-delete-installment]");if(b){pendingDelete={type:"installment",id:b.dataset.deleteInstallment};e.deleteTitle.textContent="Excluir todo o parcelamento?";e.deleteMessage.textContent="Ele deixará de ser descontado em todos os meses.";e.deleteDialog.showModal()}};e.deleteCancel.onclick=()=>{pendingDelete=null;e.deleteDialog.close()};e.deleteConfirm.onclick=confirmDelete;e.export.onclick=exportCsv;e.theme.onclick=()=>{document.body.classList.toggle("dark");const d=document.body.classList.contains("dark");localStorage.setItem(THEME_KEY,d?"dark":"light");e.theme.textContent=d?"🌙":"☀️"};if(localStorage.getItem(THEME_KEY)==="dark"){document.body.classList.add("dark");e.theme.textContent="🌙"}
supabase.auth.onAuthStateChange(async(event,session)=>{currentUser=session?.user||null;if(currentUser){showApp();if(event!=="TOKEN_REFRESHED")await loadMonth()}else{monthData={salary:0,expenses:[],installments:[]};showAuth();setSync("Desconectado")}});const{data:{session}}=await supabase.auth.getSession();currentUser=session?.user||null;if(currentUser){showApp();await loadMonth()}else showAuth();
